version: '3.8'
# Servicios
services:
  # Servicio para la base de datos MySQL
  db:
    image: mysql:8.0.34
    container_name: db
    ports:
      - '3306:3306' # Mapea el puerto 3306 del host al puerto 3306 del contenedor
    command: --default-authentication-plugin=mysql_native_password
    restart: always # Reinicia automáticamente el contenedor en caso de fallo
    environment:
      MYSQL_DATABASE: ${DB_NAME} # Nombre de la base de datos
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Contraseña del usuario root
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d # Carga archivos SQL al iniciar
      - ./docker/conf:/etc/mysql/conf.d # Carga configuraciones personalizadas
      - ./docker/mysql:/var/lib/mysql # Persistencia de datos de MySQL
    networks:
      - my_network # Conecta este servicio a la red personalizada my_network

  # Servicio para el servidor web Apache
  www:
    build: .
    container_name: www
    image: realstate:1.0 # Nombre y etiqueta de la imagen personalizada
    # logging:
      # driver: 'json-file' # Otra opción: "fluentd", "syslog", etc.
      # options:
        # max-size: '10m'
        # max-file: '3'
    ports:
      - '80:80' # Mapea el puerto 80 del host al puerto 80 del contenedor
    volumes:
      - .:/var/www/html # Monta la aplicación web en el directorio del contenedor
    networks:
      - my_network # Conecta este servicio a la red personalizada my_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Servicio para phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    ports:
      - 8000:80 # Mapea el puerto 8000 del host al puerto 80 del contenedor
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - my_network # Conecta este servicio a la red personalizada my_network

# Definición de la red personalizada
networks:
  my_network:
    name: mynetwork # Nombre de la red personalizada
